package labs;


public class Assignment {
	
	public static void main(String [] args){
		//here I create the object
		Student first = new Student("Elise", "44517444");
		Student second = new Student("Candy", "45921876");
		Student third = new Student("Jenny", "45621122");
		
		
		//here I am using abstraction to use the methods
		first.enroll("English 101");
		first.enroll("Psy201");
		first.enroll("Gov 562");
		first.showCourses();
		first.checkBalance();
		first.pay(700);
		System.out.println(first.toString());
		
		
	}

}

class Student{
	//instance variables, made private, so I can use encapsulation.  That way, it keeps the user from having access to my 
	//variables
	private String name;
	private String SSN;
	private String user;
	
	private static int ID = 100;
	private String phone;
	private String city;
	private String state;
	private String course = "";
	private int fees;
	private double newBalance;
	private int balance = 0;
	private String mySubjects;
	//needs to be set up this way, because the cost is generated by the instiution and will not change
	private static final int costOfCourse = 800;
	
	public Student(String name, String SSN){
	//this allows me to use the instance variables, and give their value to the parameter	
		this.name = name;
		String email = "@here.com";
		System.out.println(name + email);
		this.SSN = SSN;
		ID++;
		setId();
		
	}
	//calculates a random number
	private void setId(){
		int max = 9000;
		int min = 1000;
		
		int random = (int) (Math.random() *((max - min)));
		random = random + min;
		
		user = (ID + ""+ random + SSN.substring(3,7));
		
		System.out.println(user);
	}
	
	public void enroll(String course){
		//allows you to print multiple courses that you have signed up for
		this.course = this.course + "\n" +  course;
		System.out.println(course);
		balance = balance + costOfCourse;
		
		
		
	}
	
	public void pay(int fees){
		System.out.println("The amount paid: "+ fees);
		balance = balance - fees;
		System.out.println(balance);
		
		
	}
	
	public void checkBalance(){
		System.out.println("Balance: $" + balance );
	}
	
	public String toString(){
		
		return "[Name: " + name + "]\n[Courses: " + course + "]\nBalance: " + balance + "[";
		
	}
	
	public void showCourses(){
		
		System.out.println(course);
		
	}
}
